### ISSUE TITLE
Modify Join Us Button

### ISSUE THREAD

**Issue by captainkev20** [codeforgso/codeforgso.github.io#10]
## This is a: 

- [ ] bug
- [X] enhancement
- [ ] feature-discussion

# Enhancement
This button should be its own element underneath the menu that does not allow content to scroll under it.

Join Us button should be reconfigured so that it is visible once all pages

## Current Behavior
As you scroll, the Heading content will overlap and disable the button completely.

**Comment by remrobem** [comment]
per discussion on 9/10:

1. the Join Us button location should depend on the device:

- Desktop

        under navigation bar - not sticky

- Mobile

        on top of footer - sticky

2. Additional:
add arrow facing to the right in the green portion of the button
