### ISSUE TITLE
Delete Resources Page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#22]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

We have decided that we do not want a resources page at this time.

## Implementation

- Remove the `pages/resources.js` file
- Remove the link to the resources page form the navbar. (See `components/nav.js`)

**Comment by prajwalMR** [comment]
I would like to take a shot at this issue

**Comment by prajwalMR** [comment]
#27

**Comment by prajwalMR** [comment]
#27
