### ISSUE TITLE
Fix error on About page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#23]
## This is a: 

- [x] bug
- [x] enhancement
- [ ] feature-discussion

# BUG

## Current Behavior

There is a `blockquote` inside of a `p` tag and the browser considers this invalid html.

## Possible Solution

Remove the `blockquote` from within the `p` tag, but ensure the styling stays the same

## Steps to Reproduce (for bugs)

- While running the project locally, navigate to the about page, open your browser's developer tools/console. You should see the following error:
```
Warning: validateDOMNesting(...): <blockquote> cannot appear as a descendant of <p>.
    in blockquote (at about.js:12)
    in p (at about.js:10)
    in div (at about.js:9)
    in div (at about.js:8)
    in div (at page.js:14)
    in div (at page.js:13)
    in Page (at about.js:6)
    in About (created by App)
    in Container (created by App)
    in App
    in Suspense (created by AppContainer)
    in Container (created by AppContainer)
    in AppContainer
```

**Comment by ggangix** [comment]
I would like to solve this issue.
