### ISSUE TITLE
Move Hamburger (Menu Icon) to left side of navbar

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#24]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

On mobile, the [hamburger](https://en.wikipedia.org/wiki/Hamburger_button) is on the right side. It needs to be moved the left side. This also requires centering or right aligning the logo.

## Implementation

- Move the hamburger to the left side of the menu bar
- Center or right align the logo
- See [Bulma Docs](https://bulma.io/documentation/components/navbar/) for help styling/aligning navbar items.

**Comment by objNameGit** [comment]
Do you mind if I do this?

**Comment by tleisman** [comment]
Not at all, thanks!
