### ISSUE TITLE
Add hero image to home page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#26]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

Add hero image to about page. See the [figma mockups](https://www.figma.com/file/cmQXMXN6FPnOYTtUeB7Bmo/Website-Mockups?node-id=18%3A293) for the photo and an example of the layout.

## Implementation

- Copy photo from figma
- Add photo to `static` directory of project
- Update `pages/about.js` to display the photo
- Ensure it looks good on mobile and desktop

**Comment by wander-igdst** [comment]
Working on it, thanks!
