### ISSUE TITLE
npm install creating uncommitted files in package-lock.json

### ISSUE THREAD

**Issue by prajwalMR** [codeforgso/codeforgso.github.io#32]
## This is a: 

- [x] bug
- [ ] enhancement
- [ ] feature-discussion

running npm install command creates uncommitted files in package-lock.json due to changes in the versions of the node modues.

# BUG

## Expected Behavior
npm install Should not create uncommitted changes in package-lock.json

## Current Behavior
npm install is creating uncommitted changes in package-lock.json
<img width="647" alt="Screenshot 2019-10-06 at 4 57 30 PM" src="https://user-images.githubusercontent.com/15127803/66268366-6aeb0a80-e85a-11e9-95c4-03b63c33687d.png">

<img width="1204" alt="Screenshot 2019-10-06 at 4 37 27 PM" src="https://user-images.githubusercontent.com/15127803/66268370-750d0900-e85a-11e9-94f5-c3620357f297.png">

## Possible Solution
Add package-lock.json to .gitignore

## Steps to Reproduce (for bugs)

1. fork repo 
2.run "npm install"
3.run "git status"

## Your Environment
macOS mojave

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

# Enhancement

## Implementation

# Feature-Discussion

**Comment by prajwalMR** [comment]
If this issue and the possible solution can be confirmed, I would like to send a PR to fix this

**Comment by SchaeStewart** [comment]
I think I inadvertently fixed this while resolving some merge conflicts from another PR. I'm going to close this for now and will revisit if the problem persists
