### ISSUE TITLE
Add links to items in footer

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#54]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

Currently none of them items if the footer are links. Please link these items to the appropriate content

**Comment by akankshajai** [comment]
I have done this. Would you please review it?

**Comment by akankshajai** [comment]
Link To Footer Done #58
Review and Merge this PR
