### ISSUE TITLE
Fix footer styling on mobile

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#55]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

When viewing the site on mobile the footer pushes up into the view. Move the footer further down so that it does not take up so much of the screen when viewing the site on mobile.

## Implementation

Implementation is left up to the developer

**Comment by hgallop** [comment]
Is this issue resolved or does the footer need to be further reduced in size on mobile?

**Comment by braidn** [comment]
@hgallop good question. The footer styling seems to have been managed (image below) however this is a dangling issue. Do you think we can close this?

![Screen Shot 2019-11-25 at 9 22 16 AM](https://user-images.githubusercontent.com/203346/69548368-37c51d80-0f65-11ea-9563-0e74822c2f17.png)

**Comment by SchaeStewart** [comment]
I think we are good to close this.
