### ISSUE TITLE
Create Join Us page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#8]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

Add Join Us page based on Figma mockups

https://www.figma.com/file/cmQXMXN6FPnOYTtUeB7Bmo/Website-Mockups?node-id=71%3A82

## Implementation

- Create a new page component in the `pages` directory. (See index.js) for guidance
- Add the join us page to the menu

**Comment by remrobem** [comment]
per discussion on 9/10:

1. the Join Us button location should depend on the device:
- Mobile
   under navigation bar - not sticky
- Desktop
    on top of footer - sticky
2. Additional:
   add arrow facing to the right in the green portion of the button
