### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/codeforgso.github.io#9]
## This is a: 

- [ ] bug
- [x] enhancement
- [ ] feature-discussion

# Enhancement

## Description

Add About Us page based on Figma mockups

https://www.figma.com/file/cmQXMXN6FPnOYTtUeB7Bmo/Website-Mockups?node-id=18%3A293

## Implementation

- Create a new page component in the `pages` directory. (See index.js) for guidance
- Add the About page to the menu

**Comment by braidn** [comment]
The original content:

https://github.com/codeforgso/codeforgreensboro.org/blob/master/app/views/pages/about.html.erb
